### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by david-kariuki** [Davigl/github-unfollow#2]
Can this tool automatically check who is not following back?
Will I have to add all users who I don't want to unfollow. E.g Assume I have 2000 followers, will I type 2000 usernames for exclusion?

**Comment by davigl** [comment]
hey, yeah it checks who is not following back, you don't need to insert 2000 usernames!

the whitelist feature is used to prevent unfollow to some specific users.

**Comment by david-kariuki** [comment]
Ok, so that means I have to create a whitelist before running this in a case where I don't have to unfollow everyone?
Are there any more features in the oven?

**Comment by davigl** [comment]
the whitelist feature is optional, eg use: when you follow someone that doesn't follow you back and you don't wanna unfollow this person.

**Comment by davigl** [comment]
there are not features in the oven haha

**Comment by davigl** [comment]
closing

**Comment by david-kariuki** [comment]
Its ok @Davigl Thank you for your time.
